"""autogenerated by genpy from robot_comms/robotMsg.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import robot_comms.msg
import geometry_msgs.msg
import genpy
import std_msgs.msg

class robotMsg(genpy.Message):
  _md5sum = "4a84be7a3e136a2d7b8095da4b5f6e76"
  _type = "robot_comms/robotMsg"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header
string robot
string status
string goal_status
ObjectOfIntrest ooi 




================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.secs: seconds (stamp_secs) since epoch
# * stamp.nsecs: nanoseconds since stamp_secs
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: robot_comms/ObjectOfIntrest
geometry_msgs/PoseStamped position
int8 type
string name
string finder
time found_time

================================================================================
MSG: geometry_msgs/PoseStamped
# A Pose with reference coordinate frame and timestamp
Header header
Pose pose

================================================================================
MSG: geometry_msgs/Pose
# A representation of pose in free space, composed of postion and orientation. 
Point position
Quaternion orientation

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Quaternion
# This represents an orientation in free space in quaternion form.

float64 x
float64 y
float64 z
float64 w

"""
  __slots__ = ['header','robot','status','goal_status','ooi']
  _slot_types = ['std_msgs/Header','string','string','string','robot_comms/ObjectOfIntrest']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,robot,status,goal_status,ooi

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(robotMsg, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.robot is None:
        self.robot = ''
      if self.status is None:
        self.status = ''
      if self.goal_status is None:
        self.goal_status = ''
      if self.ooi is None:
        self.ooi = robot_comms.msg.ObjectOfIntrest()
    else:
      self.header = std_msgs.msg.Header()
      self.robot = ''
      self.status = ''
      self.goal_status = ''
      self.ooi = robot_comms.msg.ObjectOfIntrest()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.robot
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.goal_status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.ooi.position.header.seq, _x.ooi.position.header.stamp.secs, _x.ooi.position.header.stamp.nsecs))
      _x = self.ooi.position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7db.pack(_x.ooi.position.pose.position.x, _x.ooi.position.pose.position.y, _x.ooi.position.pose.position.z, _x.ooi.position.pose.orientation.x, _x.ooi.position.pose.orientation.y, _x.ooi.position.pose.orientation.z, _x.ooi.position.pose.orientation.w, _x.ooi.type))
      _x = self.ooi.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.ooi.finder
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.ooi.found_time.secs, _x.ooi.found_time.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ooi is None:
        self.ooi = robot_comms.msg.ObjectOfIntrest()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robot = str[start:end].decode('utf-8')
      else:
        self.robot = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8')
      else:
        self.status = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_status = str[start:end].decode('utf-8')
      else:
        self.goal_status = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.ooi.position.header.seq, _x.ooi.position.header.stamp.secs, _x.ooi.position.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ooi.position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ooi.position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.ooi.position.pose.position.x, _x.ooi.position.pose.position.y, _x.ooi.position.pose.position.z, _x.ooi.position.pose.orientation.x, _x.ooi.position.pose.orientation.y, _x.ooi.position.pose.orientation.z, _x.ooi.position.pose.orientation.w, _x.ooi.type,) = _struct_7db.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ooi.name = str[start:end].decode('utf-8')
      else:
        self.ooi.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ooi.finder = str[start:end].decode('utf-8')
      else:
        self.ooi.finder = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.ooi.found_time.secs, _x.ooi.found_time.nsecs,) = _struct_2I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_3I.pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.robot
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.goal_status
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_3I.pack(_x.ooi.position.header.seq, _x.ooi.position.header.stamp.secs, _x.ooi.position.header.stamp.nsecs))
      _x = self.ooi.position.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_7db.pack(_x.ooi.position.pose.position.x, _x.ooi.position.pose.position.y, _x.ooi.position.pose.position.z, _x.ooi.position.pose.orientation.x, _x.ooi.position.pose.orientation.y, _x.ooi.position.pose.orientation.z, _x.ooi.position.pose.orientation.w, _x.ooi.type))
      _x = self.ooi.name
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.ooi.finder
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_struct_2I.pack(_x.ooi.found_time.secs, _x.ooi.found_time.nsecs))
    except struct.error as se: self._check_types(se)
    except TypeError as te: self._check_types(te)

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.ooi is None:
        self.ooi = robot_comms.msg.ObjectOfIntrest()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.robot = str[start:end].decode('utf-8')
      else:
        self.robot = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.status = str[start:end].decode('utf-8')
      else:
        self.status = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.goal_status = str[start:end].decode('utf-8')
      else:
        self.goal_status = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.ooi.position.header.seq, _x.ooi.position.header.stamp.secs, _x.ooi.position.header.stamp.nsecs,) = _struct_3I.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ooi.position.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ooi.position.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 57
      (_x.ooi.position.pose.position.x, _x.ooi.position.pose.position.y, _x.ooi.position.pose.position.z, _x.ooi.position.pose.orientation.x, _x.ooi.position.pose.orientation.y, _x.ooi.position.pose.orientation.z, _x.ooi.position.pose.orientation.w, _x.ooi.type,) = _struct_7db.unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ooi.name = str[start:end].decode('utf-8')
      else:
        self.ooi.name = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ooi.finder = str[start:end].decode('utf-8')
      else:
        self.ooi.finder = str[start:end]
      _x = self
      start = end
      end += 8
      (_x.ooi.found_time.secs, _x.ooi.found_time.nsecs,) = _struct_2I.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_3I = struct.Struct("<3I")
_struct_7db = struct.Struct("<7db")
_struct_2I = struct.Struct("<2I")
