/* Auto-generated by genmsg_cpp for file /home/liampoli/ROS_Packages/robot_comms/srv/ImageFilter.srv */
#ifndef ROBOT_COMMS_SERVICE_IMAGEFILTER_H
#define ROBOT_COMMS_SERVICE_IMAGEFILTER_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "ros/service_traits.h"




namespace robot_comms
{
template <class ContainerAllocator>
struct ImageFilterRequest_ {
  typedef ImageFilterRequest_<ContainerAllocator> Type;

  ImageFilterRequest_()
  : filter_id(0)
  {
  }

  ImageFilterRequest_(const ContainerAllocator& _alloc)
  : filter_id(0)
  {
  }

  typedef int64_t _filter_id_type;
  int64_t filter_id;


  typedef boost::shared_ptr< ::robot_comms::ImageFilterRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comms::ImageFilterRequest_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ImageFilterRequest
typedef  ::robot_comms::ImageFilterRequest_<std::allocator<void> > ImageFilterRequest;

typedef boost::shared_ptr< ::robot_comms::ImageFilterRequest> ImageFilterRequestPtr;
typedef boost::shared_ptr< ::robot_comms::ImageFilterRequest const> ImageFilterRequestConstPtr;


template <class ContainerAllocator>
struct ImageFilterResponse_ {
  typedef ImageFilterResponse_<ContainerAllocator> Type;

  ImageFilterResponse_()
  : result(0)
  {
  }

  ImageFilterResponse_(const ContainerAllocator& _alloc)
  : result(0)
  {
  }

  typedef int64_t _result_type;
  int64_t result;


  typedef boost::shared_ptr< ::robot_comms::ImageFilterResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_comms::ImageFilterResponse_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct ImageFilterResponse
typedef  ::robot_comms::ImageFilterResponse_<std::allocator<void> > ImageFilterResponse;

typedef boost::shared_ptr< ::robot_comms::ImageFilterResponse> ImageFilterResponsePtr;
typedef boost::shared_ptr< ::robot_comms::ImageFilterResponse const> ImageFilterResponseConstPtr;

struct ImageFilter
{

typedef ImageFilterRequest Request;
typedef ImageFilterResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;
}; // struct ImageFilter
} // namespace robot_comms

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comms::ImageFilterRequest_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comms::ImageFilterRequest_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comms::ImageFilterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "df5b073eb2c62b846cf973c597df7ad7";
  }

  static const char* value(const  ::robot_comms::ImageFilterRequest_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0xdf5b073eb2c62b84ULL;
  static const uint64_t static_value2 = 0x6cf973c597df7ad7ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comms::ImageFilterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comms/ImageFilterRequest";
  }

  static const char* value(const  ::robot_comms::ImageFilterRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comms::ImageFilterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 filter_id\n\
\n\
\n\
";
  }

  static const char* value(const  ::robot_comms::ImageFilterRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robot_comms::ImageFilterRequest_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros


namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::robot_comms::ImageFilterResponse_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::robot_comms::ImageFilterResponse_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::robot_comms::ImageFilterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "9b05623554ab950ed237d43d45f0b4dd";
  }

  static const char* value(const  ::robot_comms::ImageFilterResponse_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x9b05623554ab950eULL;
  static const uint64_t static_value2 = 0xd237d43d45f0b4ddULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_comms::ImageFilterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comms/ImageFilterResponse";
  }

  static const char* value(const  ::robot_comms::ImageFilterResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::robot_comms::ImageFilterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "int64 result\n\
\n\
\n\
";
  }

  static const char* value(const  ::robot_comms::ImageFilterResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::robot_comms::ImageFilterResponse_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comms::ImageFilterRequest_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.filter_id);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ImageFilterRequest_
} // namespace serialization
} // namespace ros


namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::robot_comms::ImageFilterResponse_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.result);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct ImageFilterResponse_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace service_traits
{
template<>
struct MD5Sum<robot_comms::ImageFilter> {
  static const char* value() 
  {
    return "80825786ac8e53e4ca138e168c03ada7";
  }

  static const char* value(const robot_comms::ImageFilter&) { return value(); } 
};

template<>
struct DataType<robot_comms::ImageFilter> {
  static const char* value() 
  {
    return "robot_comms/ImageFilter";
  }

  static const char* value(const robot_comms::ImageFilter&) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comms::ImageFilterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "80825786ac8e53e4ca138e168c03ada7";
  }

  static const char* value(const robot_comms::ImageFilterRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comms::ImageFilterRequest_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comms/ImageFilter";
  }

  static const char* value(const robot_comms::ImageFilterRequest_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct MD5Sum<robot_comms::ImageFilterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "80825786ac8e53e4ca138e168c03ada7";
  }

  static const char* value(const robot_comms::ImageFilterResponse_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct DataType<robot_comms::ImageFilterResponse_<ContainerAllocator> > {
  static const char* value() 
  {
    return "robot_comms/ImageFilter";
  }

  static const char* value(const robot_comms::ImageFilterResponse_<ContainerAllocator> &) { return value(); } 
};

} // namespace service_traits
} // namespace ros

#endif // ROBOT_COMMS_SERVICE_IMAGEFILTER_H

