/* Auto-generated by genmsg_cpp for file /home/wambot/ros_workspace/cmvision/msg/Blob.msg */
#ifndef CMVISION_MESSAGE_BLOB_H
#define CMVISION_MESSAGE_BLOB_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"


namespace cmvision
{
template <class ContainerAllocator>
struct Blob_ {
  typedef Blob_<ContainerAllocator> Type;

  Blob_()
  : red(0)
  , green(0)
  , blue(0)
  , area(0)
  , x(0)
  , y(0)
  , left(0)
  , right(0)
  , top(0)
  , bottom(0)
  {
  }

  Blob_(const ContainerAllocator& _alloc)
  : red(0)
  , green(0)
  , blue(0)
  , area(0)
  , x(0)
  , y(0)
  , left(0)
  , right(0)
  , top(0)
  , bottom(0)
  {
  }

  typedef uint32_t _red_type;
  uint32_t red;

  typedef uint32_t _green_type;
  uint32_t green;

  typedef uint32_t _blue_type;
  uint32_t blue;

  typedef uint32_t _area_type;
  uint32_t area;

  typedef uint32_t _x_type;
  uint32_t x;

  typedef uint32_t _y_type;
  uint32_t y;

  typedef uint32_t _left_type;
  uint32_t left;

  typedef uint32_t _right_type;
  uint32_t right;

  typedef uint32_t _top_type;
  uint32_t top;

  typedef uint32_t _bottom_type;
  uint32_t bottom;


  typedef boost::shared_ptr< ::cmvision::Blob_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::cmvision::Blob_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Blob
typedef  ::cmvision::Blob_<std::allocator<void> > Blob;

typedef boost::shared_ptr< ::cmvision::Blob> BlobPtr;
typedef boost::shared_ptr< ::cmvision::Blob const> BlobConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::cmvision::Blob_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::cmvision::Blob_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace cmvision

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::cmvision::Blob_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::cmvision::Blob_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::cmvision::Blob_<ContainerAllocator> > {
  static const char* value() 
  {
    return "56ed098ed179c6b791d85398b11f5ff6";
  }

  static const char* value(const  ::cmvision::Blob_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x56ed098ed179c6b7ULL;
  static const uint64_t static_value2 = 0x91d85398b11f5ff6ULL;
};

template<class ContainerAllocator>
struct DataType< ::cmvision::Blob_<ContainerAllocator> > {
  static const char* value() 
  {
    return "cmvision/Blob";
  }

  static const char* value(const  ::cmvision::Blob_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::cmvision::Blob_<ContainerAllocator> > {
  static const char* value() 
  {
    return "uint32 red\n\
uint32 green\n\
uint32 blue\n\
uint32 area\n\
uint32 x\n\
uint32 y\n\
uint32 left\n\
uint32 right\n\
uint32 top\n\
uint32 bottom\n\
\n\
";
  }

  static const char* value(const  ::cmvision::Blob_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct IsFixedSize< ::cmvision::Blob_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::cmvision::Blob_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.red);
    stream.next(m.green);
    stream.next(m.blue);
    stream.next(m.area);
    stream.next(m.x);
    stream.next(m.y);
    stream.next(m.left);
    stream.next(m.right);
    stream.next(m.top);
    stream.next(m.bottom);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Blob_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::cmvision::Blob_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::cmvision::Blob_<ContainerAllocator> & v) 
  {
    s << indent << "red: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.red);
    s << indent << "green: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.green);
    s << indent << "blue: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.blue);
    s << indent << "area: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.area);
    s << indent << "x: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.y);
    s << indent << "left: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.right);
    s << indent << "top: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.top);
    s << indent << "bottom: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.bottom);
  }
};


} // namespace message_operations
} // namespace ros

#endif // CMVISION_MESSAGE_BLOB_H

